/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.chart.BatteryChart;
import controller.chart.PingChart;
import controller.reporter.PingReporter;
import controller.reporter.BatteryReporter;
import controller.extractor.BatteryStateExtractor;
import controller.extractor.PingStateExtractor;

/**
 *
 * @author lucasew
 */
public class UIDashboard extends javax.swing.JFrame implements Runnable {

    private final PingReporter pingTask;
    private final BatteryReporter powerTask;

    public UIDashboard(PingReporter pingTask, BatteryReporter powerTask) {
        this.pingTask = pingTask;
        this.powerTask = powerTask;
        initComponents();
        this.setTitle("Dashboard - Monitor de Recursos");
    }

    @Override
    public void run() {
        this.btnDashboardPing.setExtractor(new PingStateExtractor(pingTask, 1000));
        this.btnDashboardBat.setExtractor(new BatteryStateExtractor(powerTask));
        Thread btnDashboardBatDaemon = new Thread(btnDashboardBat);
        Thread btnDashboardPingDaemon = new Thread(btnDashboardPing);
        btnDashboardBatDaemon.start();
        btnDashboardPingDaemon.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboardPing = new view.components.DashboardButton();
        btnDashboardBat = new view.components.DashboardButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDashboardPing.setText("dashboardButton1");
        btnDashboardPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardPingActionPerformed(evt);
            }
        });

        btnDashboardBat.setText("dashboardButton2");
        btnDashboardBat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardBatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDashboardBat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDashboardPing, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnDashboardPing, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDashboardBat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardPingActionPerformed
        PingChart chart = new PingChart();
        chart.setLocationRelativeTo(null);
        chart.setSize(800, 600);
        chart.setVisible(true);
    }//GEN-LAST:event_btnDashboardPingActionPerformed

    private void btnDashboardBatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardBatActionPerformed
        BatteryChart chart = new BatteryChart();
        chart.setLocationRelativeTo(null);
        chart.setSize(800, 600);
        chart.setVisible(true);
    }//GEN-LAST:event_btnDashboardBatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.components.DashboardButton btnDashboardBat;
    private view.components.DashboardButton btnDashboardPing;
    // End of variables declaration//GEN-END:variables
}
