/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import controller.lifecycle.Closeable;
import controller.lifecycle.DestroyWindowEventHandler;
import controller.lifecycle.WindowCounter;
import model.exception.SingleInstanceException;

/**
 *
 * @author lucasew
 */
public class UIPaginaInicial extends javax.swing.JFrame implements Closeable {

    public UIPaginaInicial() {
        initComponents();
        WindowCounter.increment();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.addWindowListener(new DestroyWindowEventHandler(this));
    }

    public static void main(String[] args) {
        new UIPaginaInicial().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBemVindo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciarMonitoramento = new javax.swing.JButton();
        btnExibirRelatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblBemVindo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblBemVindo.setText("Bem Vindo");

        jLabel1.setText("O que deseja fazer?");

        btnIniciarMonitoramento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/icon/captura_dados.png"))); // NOI18N
        btnIniciarMonitoramento.setText("Iniciar monitoramento");
        btnIniciarMonitoramento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIniciarMonitoramento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarMonitoramentoActionPerformed(evt);
            }
        });

        btnExibirRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/icon/device.png"))); // NOI18N
        btnExibirRelatorios.setText("Exibir Relatórios");
        btnExibirRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExibirRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBemVindo)
                .addGap(0, 68, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnIniciarMonitoramento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExibirRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarMonitoramento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExibirRelatorios)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarMonitoramentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarMonitoramentoActionPerformed
        try {
            new UIDashboard().setVisible(true);
        } catch (IOException ex) {
            MessageBoxBuilder.showError("Não foi possível realizar a detecção do nome da máquina");
        } catch (SingleInstanceException ex) {
            MessageBoxBuilder.showError("Apenas uma janela de monitoramento é permitida no programa");
        }
    }//GEN-LAST:event_btnIniciarMonitoramentoActionPerformed

    private void btnExibirRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirRelatoriosActionPerformed
        new UISelecionarHostname().setVisible(true);
    }//GEN-LAST:event_btnExibirRelatoriosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExibirRelatorios;
    private javax.swing.JButton btnIniciarMonitoramento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBemVindo;

    @Override
    public void close() {
        WindowCounter.decrement();
    }
    // End of variables declaration//GEN-END:variables
}
