/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.lifecycle.Closeable;
import controller.lifecycle.DestroyWindowEventHandler;
import controller.lifecycle.WindowCounter;
import controller.chart.BatteryChart;
import controller.chart.PingChart;
import controller.database.MachineController;

import java.util.ArrayList;
import java.util.List;

import view.components.ChartViewer;

/**
 *
 * @author lucasew
 */
public class UISelecionarHostname extends javax.swing.JFrame implements Closeable {
    List<String> machines = new ArrayList<String>() {{
        MachineController
                .getAllMachines()
                .stream()
                .forEach(m -> add(m.toString()));
    }};
    String selected = machines.get(0);

    public static void main(String[] args) {
        new UISelecionarHostname().setVisible(true);
    }

    /**
     * Creates new form UISelecionarHostname
     */
    public UISelecionarHostname() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        WindowCounter.increment();
        this.addWindowListener(new DestroyWindowEventHandler(this));
        setResizable(false);
    }

    public void close() {
        WindowCounter.decrement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblInstrucao = new javax.swing.JLabel();
        comboSelecao = new javax.swing.JComboBox<>();
        btnBateria = new javax.swing.JButton();
        btnInternet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInstrucao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblInstrucao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstrucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/icon/device.png"))); // NOI18N
        lblInstrucao.setText("Selecione o dispositivo que deseja exibir o relatório");
        lblInstrucao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblInstrucao.setFocusable(false);
        lblInstrucao.setMaximumSize(new java.awt.Dimension(730, 72));

        comboSelecao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${machines}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboSelecao);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${selected}"), comboSelecao, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        btnBateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/icon/battery.png"))); // NOI18N
        btnBateria.setText("Estado de Bateria");
        btnBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBateriaActionPerformed(evt);
            }
        });

        btnInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/icon/sinal_bom.png"))); // NOI18N
        btnInternet.setText("Estado da Internet");
        btnInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInternetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInternet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboSelecao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInstrucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBateriaActionPerformed
        new ChartViewer(new BatteryChart(MachineController.getMachine(this.selected))).run();
    }//GEN-LAST:event_btnBateriaActionPerformed

    private void btnInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternetActionPerformed
        new ChartViewer(new PingChart(MachineController.getMachine(this.selected))).run();
    }//GEN-LAST:event_btnInternetActionPerformed

    public List<String> getMachines() {
        return machines;
    }

    public void setMachines(List<String> machines) {
        this.machines = machines;
    }

    public String getSelected() {
        return selected;
    }

    public void setSelected(String selected) {
        this.selected = selected;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBateria;
    private javax.swing.JButton btnInternet;
    private javax.swing.JComboBox<String> comboSelecao;
    private javax.swing.JLabel lblInstrucao;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
